# Generated by Django 6.0.3 on 2026-03-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage_phone_contactmessage_student_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('image', models.ImageField(upload_to='gallery/images/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GalleryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('Events', 'Events'), ('Sports', 'Sports'), ('Academics', 'Academics')], default='Events', max_length=20)),
                ('duration', models.CharField(blank=True, default='', max_length=20)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('tiktok', 'TikTok')], default='youtube', max_length=20)),
                ('youtube_id', models.CharField(blank=True, default='', max_length=100)),
                ('tiktok_id', models.CharField(blank=True, default='', max_length=100)),
                ('thumbnail_url', models.URLField(blank=True, default='')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
