# Generated by Django 6.0.3 on 2026-03-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_galleryimage_galleryvideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ('display_order', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='galleryvideo',
            options={'ordering': ('display_order', '-created_at')},
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='galleryvideo',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
