# Generated by Django 6.0.3 on 2026-03-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_galleryimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('Latest', 'Latest News'), ('Events', 'Past & Upcoming Events'), ('Calendar', 'Academic Calendar')], default='Latest', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('date_text', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('section', 'display_order', '-created_at'),
            },
        ),
    ]
